create table if not exists public.smartcart_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null default '',
  plan text not null default 'free' check (plan in ('free', 'plus')),
  beta_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.smartcart_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  provider text not null default 'stripe',
  plan text not null default 'free' check (plan in ('free', 'plus')),
  status text not null default 'inactive',
  provider_customer_id text,
  provider_subscription_id text,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_smartcart_profiles_updated_at on public.smartcart_profiles;
create trigger set_smartcart_profiles_updated_at
before update on public.smartcart_profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_smartcart_subscriptions_updated_at on public.smartcart_subscriptions;
create trigger set_smartcart_subscriptions_updated_at
before update on public.smartcart_subscriptions
for each row
execute function public.set_updated_at();

alter table public.smartcart_profiles enable row level security;
alter table public.smartcart_subscriptions enable row level security;

drop policy if exists "Users can view their own SmartCart profile" on public.smartcart_profiles;
create policy "Users can view their own SmartCart profile"
on public.smartcart_profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can insert their own SmartCart profile" on public.smartcart_profiles;
create policy "Users can insert their own SmartCart profile"
on public.smartcart_profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update their own SmartCart profile" on public.smartcart_profiles;
create policy "Users can update their own SmartCart profile"
on public.smartcart_profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can view their own SmartCart subscriptions" on public.smartcart_subscriptions;
create policy "Users can view their own SmartCart subscriptions"
on public.smartcart_subscriptions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own SmartCart subscriptions" on public.smartcart_subscriptions;
create policy "Users can insert their own SmartCart subscriptions"
on public.smartcart_subscriptions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own SmartCart subscriptions" on public.smartcart_subscriptions;
create policy "Users can update their own SmartCart subscriptions"
on public.smartcart_subscriptions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
